name: Angular app test Deployment

on:
  push:
    branches:
    - master  

jobs:
  build:
    runs-on: ubuntu-latest
     
    container:
      image: node:12  # Use a Node.js 12 Docker image
    env:
      APP_DIRECTORY: '../../src/app'   #Our source directory

    # strategy:
    #   matrix:
    #     environment: [QA, Production]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2


      - name: Set Up Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
      # - name: Use Node.js $
      #   uses: actions/setup-node@v1
      #   # with:
      #   #   node-version: latest

      - name: Install dependencies
        run: npm install -g @angular/cli
        
      - name: Build
        run: ng build

      - name: Archive Build Artifacts
        uses: actions/upload-artifact@v2
        with:
           name: dist
           path: dist  # This assumes your built Angular app is in a "dist" directory

      # - name: Set Environment Variables
      #   run: |
      #     echo "APP_DIRECTORY=$APP_DIRECTORY" >> $GITHUB_ENV
      #     echo "ENVIRONMENT=${{ matrix.environment }}" >> $GITHUB_ENV