name: Frontend Build-Only Pipeline

on:
  push:
    
  pull_request:
        branches:
          - Development
          - master

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        # with:
        #   node-version: 12
        
      - name: Install NPM Dependencies
        run:  npm install --force

      - name: Install Angular@9
        run: npm install -g @angular/cli
    #   - name: Remove Existing 'ng-uikit-pro-standard'
    #     run:  rm -rf node_modules/ng-uikit-pro-standard

    #   - name: Copy New 'ng-uikit-pro-standard'
    #     run: |
    #          mkdir -p node_modules
    #          cp -r ng-uikit-pro-standard node_modules/
      - name: Build Code
        run: |
          ng buildxxx
          if [ $? -eq 0 ]; then
             echo "::set-output name=status::success"
          else
          echo "::set-output name=status::failure"
          echo "Build hasbeen failed and PR is getting close"
          PR_NUMBER="${{ github.event.pull_request.number }}"
          API_URL="https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER"
          PAYLOAD='{"state":"closed"}'

          echo "Closing PR $PR_NUMBER due to build failure"
          
          # Close the PR
          curl -X PATCH -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "$PAYLOAD" \
            "$API_URL"
           fi
        id: build-status
        # continue-on-error: true # Continue even if the build fails
          # node --max-old-space-size=8192 ./node_modules/@angular/cli/bin/ng build
  # close-pr:
  #     needs: build
  #     runs-on: ubuntu-latest
  #     steps:
  #       - name: Close PR on Build Failure
  #         if: ${{ needs.build.outputs.status == 'failure' }}
          
  