name: Frontend Build-Only Pipeline

on:
  push:
    
  pull_request:
        branches:
          - Dev-test
          - master

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        # with:
        #   node-version: 12
        
 
      - name: Install NPM Dependencies
        run:  npm install --force

      - name: Install Angular@9
        run: npm install -g @angular/cli
         abcdefghi
    #   - name: Remove Existing 'ng-uikit-pro-standard'
    #     run:  rm -rf node_modules/ng-uikit-pro-standard

    #   - name: Copy New 'ng-uikit-pro-standard'
    #     run: |
    #          mkdir -p node_modules
    #          cp -r ng-uikit-pro-standard node_modules/
      
      - name: Build Code
        run: |
         ng build
         echo "::set-output name=status::success" # Set the initial status as success
 # node --max-old-space-size=8192 ./node_modules/@angular/cli/bin/ng build
      - name: Determine Build Status
        id: check-build-status
        run: |
          if [ -d "dist" ]; then
            echo "::set-output name=status::success"
          else
            echo "::set-output name=status::failure"
          fi

      - name: Close or Deprecate PR
        if: steps.check-build-status.outputs.status == 'failure'
        run: |
          # You can add your logic to close or deprecate the PR here
          # Example: Close the PR
          # GITHUB_TOKEN is a built-in token for authentication
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"state": "closed"}' \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}"


