name: Angular app test Deployment

on:
  push:
    branches:
    - master  

jobs:
  build:
    runs-on: ubuntu-latest
     
    container:
      image: node:12  # Use a Node.js 12 Docker image
    env:
      APP_DIRECTORY: '../../src/app'   #Our source directory


    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2


      - name: Set Up Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Install dependencies
        run: npm install -g @angular/cli
        
      - name: Build
        run: ng build

      - name: Archive Build Artifacts
        uses: actions/upload-artifact@v2
        with:
           name: dist
           path: dist  

      # - name: Set Environment Variables
      #   run: |
      #     echo "APP_DIRECTORY=$APP_DIRECTORY" >> $GITHUB_ENV
      #     echo "ENVIRONMENT=${{ matrix.environment }}" >> $GITHUB_ENV