name: Angular Deployment

on:
  workflow_dispatch: # This event allows manual triggering of the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Choose Deployment Environment
        run: |
          echo "Which environment do you want to deploy to?"
          read -p "Enter 'dev' or 'prod': " ENV_CHOICE
          if [ "$ENV_CHOICE" != "dev" ] && [ "$ENV_CHOICE" != "prod" ]; then
            echo "Invalid environment choice. Please enter 'dev' or 'prod'."
            exit 1
          fi
          echo "::set-output name=env_choice::$ENV_CHOICE"
        shell: bash

      - name: Build and Deploy
        run: |
          ENV_CHOICE="${{ steps.choose-deployment-environment.outputs.env_choice }}"
          if [ "$ENV_CHOICE" == "dev" ]; then
            npm run build -- --configuration=development
          else
            npm run build -- --configuration=production
          fi
          # Add AWS Amplify deployment commands here for the chosen environment
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2 # Change to your region
          # Add other environment-specific secrets as needed



