name: Automate Deploy Angular app

env:
  APP_LOCATION: "src"
  API_LOCATION: "" 
  OUTPUT_LOCATION: "dist/test-app" 

on:
 push:
      branches:
        - master 
        - test
 workflow_dispatch:
    inputs:
      release Type:
       description: 'Where to release( angular or test)?'
       required: True
       default:  'test'    
   # release:
   #   types: [published]
 
jobs:
 test:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: ${{ env.APP_LOCATION }}
          api_location: ${{ env.API_LOCATION }}
          output_location: ${{ env.OUTPUT_LOCATION }}
          # app_build_command: 'npm run build'
          app_build_command: 'ng build --prod'

    
     
