name: Release Pipeline

on:
  workflow_run:
    workflows: ["Build Pipeline"] # Replace with the name of your build workflow
    types:
      - completed

  pull_request_review:
    types:
      - submitted
jobs:
  release:
    runs-on: ubuntu-latest
    needs: Build
    strategy:
      matrix:
        environment: [QA, Production]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Build Artifacts
        uses: actions/download-artifact@v2
        with:
          name: dist

      # Uncomment the following lines to set environment variables
      # - name: Set environment variables
      #   run: |
      #     echo "APP_DIRECTORY=$APP_DIRECTORY" >> $GITHUB_ENV 
      #     echo "ENVIRONMENT=${{ matrix.environment }}" >> $GITHUB_ENV

      # Uncomment the following block to trigger the Build Pipeline workflow
      # - name: Trigger Build Pipeline
      #   uses: octokit/request-action@v2
      #   with:
      #     route: POST /repos/${{ github.repository }}/actions/workflows/<YOUR_BUILD_WORKFLOW_ID>/dispatches
      #     token: ${{ secrets.GITHUB_TOKEN }}
