name: Conditional Release Pipeline

on:
  workflow_run:
    workflows: ["Frontend Build-Only Pipeline"] 
    types:
    - completed
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  check-pr-status:
    runs-on: ubuntu-latest
    steps:
    - name: Check Build Status
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Extract information about the triggering workflow run
        EVENT_PAYLOAD=$(cat $GITHUB_EVENT_PATH)
        TRIGGERING_WORKFLOW_NAME=$(jq -r '.workflow.name' <<< "$EVENT_PAYLOAD")
        TRIGGERING_WORKFLOW_STATUS=$(jq -r '.workflow_run.conclusion' <<< "$EVENT_PAYLOAD")
        
        # Check if the triggering workflow was successful
        if [ "$TRIGGERING_WORKFLOW_STATUS" == "success" ]; then
          echo "Congragulation! The triggering workflow ($TRIGGERING_WORKFLOW_NAME) was successful."
          # You can add further steps here if you need to take action based on success.
        else
          echo "OOps! The triggering workflow ($TRIGGERING_WORKFLOW_NAME) failed or had another conclusion."
          # You can add further steps here if you need to take action based on failure.
        fi
      # ---------------------------abcdef--------------------------
 
