name: Conditional Release Pipeline

on:
  workflow_run:
    workflows: ["Frontend Build-Only Pipeline"] 
  #   types:
  #   - completed
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  check-buildpipeline-status:
    runs-on: ubuntu-latest
    steps:
    - name: Check Build Status
      id: check-build-status
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Extract information about the triggering workflow run
        EVENT_PAYLOAD=$(cat $GITHUB_EVENT_PATH)
        TRIGGERING_WORKFLOW_NAME=$(jq -r '.workflow.name' <<< "$EVENT_PAYLOAD")
        TRIGGERING_WORKFLOW_STATUS=$(jq -r '.workflow_run.conclusion' <<< "$EVENT_PAYLOAD")
        
        # Check if the triggering workflow was successful
        if [ "$TRIGGERING_WORKFLOW_STATUS" == "success" ]; then
          echo "Congragulation! The triggering workflow ($TRIGGERING_WORKFLOW_NAME) was successful."
          echo "::set-output name=build-failed::false"
        else
          echo "OOps! The triggering workflow ($TRIGGERING_WORKFLOW_NAME) failed or had another conclusion."
          echo "::set-output name=build-failed::true"


    - name: Deprecate PR on Build Failure
      if: steps.check-build-status.outputs.build-failed == 'true'
      run: |
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/axmaijaz/repo1/pulls/${{ github.event.pull_request.number }}/update -d '{"state":"closed"}'
          fi
      # -----------------------------------------------------
 
    